# Octoprint notes and configuration

########################################
### Installing and running Octoprint ###
########################################

# 1. Start the octoprint server:
#
#    $ sudo systemctl start octoprint
#
# 2. (optional) Start mjpg_streamer to stream the webcam:
#
#    $ mjpg_streamer -i "input_uvc.so -n -r VGA -f 5 -q 50" -o "output_http.so -w ./www -p 5001"
#
# 3. (optional) Start a proxy to access Octoprint remotely
#
#    $ ngrok start --all # see ~/ngrok/.ngrok

#################################
### Resources and integration ###
#################################

# Octoprint
#   Octoprint is the main server for interacting with the printer.
#   Plugins: Detailed Progress, M73 Progress, Octolapse, Octopod
#
# Octoclient
#   Octoclient is the official iPhone app for Octoprint.
#   Alternative: Octopod
#
# Thingiverse
#   Thingiverse is the primary source of patterns and things.
#
# Ultimaker Cura
#   Cura let's you download STL files (ie from thingiverse), modify
#   the print settings, and export them as .gcode to print.
#   Plugins: Octoprint plugin to use the "Monitor" tab.
#
# OpenSCAD
#   OpenSCAD let's you download SCAR files (ie from thingiverse) and
#   modify the code, render, and export as STL, which can then be
#   imported to Cura and printed.

############################################
### Webcam configuration (Logitech C270) ###
############################################

webcam:
  ffmpeg: /usr/bin/ffmpeg
  snapshot: https://cr-mjpg-stream.ngrok.io/?action=snapshot
  snapshotSslValidation: false
  stream: https://cr-mjpg-stream.ngrok.io/?action=stream
  timelapse:
    fps: 25
    options:
      interval: 10
    postRoll: 0
    type: timed
  watermark: false
