#!/usr/bin/env sh

# amu - Control Amazon Music Unlimited from the CLI using xdotool
#
# Usage:
#
# 1. Setting up Amazon Music Unlimited
#    I have Amazon Music running in Chrome as a standalone chrome app:
#
#    $ google-chrome --app=https://music.amazon.com
#
#    This makes it feel like it's own app with no URL bar, etc.
#
# 2. Commands
#
#    $ amu next # next track
#    $ amu prev # previous track
#    $ amu pause # pause/unpause

nextTrack() {
    WINDOW=$(xdotool getactivewindow)
    xdotool search --limit 1 --name "Amazon Music" windowfocus key Right;
    xdotool windowfocus $WINDOW;
}

prevTrack() {
    WINDOW=$(xdotool getactivewindow)
    xdotool search --limit 1 --name "Amazon Music" windowfocus key Left;
    xdotool windowfocus $WINDOW;
}

pauseTrack() {
    WINDOW=$(xdotool getactivewindow)
    xdotool search --limit 1 --name "Amazon Music" windowfocus key space;
    xdotool windowfocus $WINDOW;
}

if [[ "$1" == "next" ]]; then
    nextTrack
elif [[ "$1" == "prev" ]]; then
    prevTrack
elif [[ "$1" == "pause" ]]; then
    pauseTrack
fi
