#!/usr/bin/python

import imaplib
import os

home_env = os.environ["HOME"]
passphrase_file = open(home_env + "/.scripts/.mailauth")
passphrase = passphrase_file.readline()

# default imap port is 993, change otherwise
M=imaplib.IMAP4_SSL("imap.gmail.com", 993)
M.login("cody@reichertbrothers.com", passphrase)

status, counts = M.status("Inbox","(MESSAGES UNSEEN)")

unread = counts[0].split()[4][:-1]

mailcount_file = open(home_env + "/.scripts/mailcount", "w")
mailcount_file.write(unread)
mailcount_file.close()

M.logout()
