#!/bin/bash

#cmus status
status=$(cmus-remote -Q | grep "status")

# song info
title=$(cmus-remote -Q | sed -n 's/tag title \(.*\)/\1/p');
title=$(echo $title | sed 's/\"/\\\"/g');
artist=$(cmus-remote -Q | sed -n 's/tag artist \(.*\)/\1/p');

# output text depending on status
if [[ $status == "status paused" ]];
then
    echo "$artist - $title (paused) " > /home/cody/.scripts/nowplaying
    exit

elif [[ $status == "status stopped" ]];
then
    echo "" > /home/cody/.scripts/nowplaying
    exit
elif [[ $status == "status playing" ]];
then
    echo "$artist - $title " > /home/cody/.scripts/nowplaying
    exit
else
    echo ""
fi
