#!/bin/bash
#
# Usage:
#   $ workbox [application]
#
# Calling this script will do one of three things:
#   1. Focus $application window if it exists.
#   2. Minimize $application window if it is already focused.
#   3. Launch $application if no window exists.

application=$1
window_id=$(xdotool search $application | tail -n 1)
active_win_id=$(xdotool getactivewindow)

if [ -z "$window_id" ]; then
    # Launch $application if no windows exist
    ($application) &
elif [ "$active_win_id" == "$window_id" ]; then
    # Minimize $application window
    xdotool windowminimize $window_id
else
    # Focus $application window
    xdotool windowactivate $window_id
fi
