#!/usr/bin/env bash

usage () {
    echo "Usage: wp-site [-s <string> | -i <string>] [-p <string>]"
    echo "  -s: Create a new site (wp-site -s <site-name/slug>)"
    echo "  -p: Install a new plugin (wp-site -p <plugin-name>)"
    1>&2;
    exit 1;
}


while getopts ":s:i:p:" o; do
    case "${o}" in
        s)
            docker-compose run wordpress wp --allow-root site create \
                           --title=${OPTARG} \
                           --slug=${OPTARG}
            ;;
        i)
            docker-compose run wordpress wp --allow-root site create --prompt
            ;;
        p)
            docker-compose run wordpress wp \
                           --allow-root plugin install ${OPTARG} \
            ;;
        *)
            usage
            ;;
    esac
done

shift $((OPTIND-1))

if [ -z "${s}" ] || [ -z "${p}" ] || [ -z "${i}" ] ; then
    usage
fi

echo "s = ${s}"
echo "p = ${p}"
echo "i = ${i}"
