directory: /media/cody/ASPEN/music/tagged
library: /media/cody/ASPEN/music/data/musiclibrary.blb

plugins: fetchart web mpdstats

import:
  copy: yes
  quiet_fallback: skip
  log: /media/cody/ASPEN/music/data/imported-beets.log

web:
  host: 192.168.1.101
  port: 1234

fetchart:
  google_search: true

mpdstats:
  music_directory: /media/cody/ASPEN/music/tagged/