directory: ~/music/tagged/
library: ~/music/data/musiclibrary.blb

plugins: fetchart web

import:
  copy: yes
  quiet_fallback: skip
  log: ~/music/data/imported-beets.log

web:
  host: 192.168.1.101
  port: 1234

fetchart:
  google_search: true
